[package]
name = "pallet-frequency-tx-payment-runtime-api"
version = "0.0.0"
description = "A package that adds Runtime Api for payment pallet"
authors = ["Frequency"]
license = "Apache-2.0"
publish = false
homepage = "https://frequency.xyz"
repository = "https://github.com/LibertyDSNP/frequency/"
edition = "2021"

[dependencies]
codec = { package = "parity-scale-codec", version = "3.2.2", default-features = false, features = [
	"derive"
] }
# Substrate
sp-api = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v1.0.0" }
sp-std = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v1.0.0" }
frame-support = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v1.0.0" }
# Frequency related dependencies
common-primitives = { default-features = false, path = "../../../../common/primitives" }
pallet-transaction-payment = {default-features = false, git = "https://github.com/paritytech/substrate", branch = "polkadot-v1.0.0" }

[features]
default = ['std']
std = [
	"codec/std",
	"sp-api/std",
	"sp-std/std",
	"frame-support/std",
	"common-primitives/std",
	"pallet-transaction-payment/std"
]
