[package]
name = "pallet-messages-rpc"
version = '0.1.0'
description = 'A package that adds RPC to Messages pallet'
authors = ['Frequency Team']
license = "Apache-2.0"
publish = false
homepage = "https://frequency.xyz"
repository = "https://github.com/LibertyDSNP/frequency/"
edition = "2021"

[dependencies]
codec = { package = "parity-scale-codec", version = "3.1.5" }
jsonrpsee = { version = "0.15.1", features = ["server", "macros"] }

# unfinished
pallet-messages-runtime-api = {default-features = false, path = "../runtime-api" }
common-primitives = {default-features = false, path = "../../../../common/primitives" }
common-helpers = {default-features = false, path = "../../../../common/helpers" }
# Substrate packages
sp-api = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.29" }
sp-blockchain = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.29" }
sp-runtime = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.29" }
frame-support = { default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.29" }

[dev-dependencies]
tokio = { version = "1.21.2", features = ["macros", "time", "parking_lot"] }
substrate-test-runtime-client = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.29" }
sc-client-api = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.29" }

[features]
default = ["std"]
std = [
	'codec/std',
	"sp-api/std",
	"sp-runtime/std",
	'frame-support/std',
	"pallet-messages-runtime-api/std",
	'common-primitives/std',
]
