[package]
name = "pallet-messages-rpc"
version = '0.1.0'
description = 'A package that adds RPC to Messages pallet'
authors = ['Frequency Team']
license = "Apache-2.0"
publish = false
homepage = "https://frequency.xyz"
repository = "https://github.com/LibertyDSNP/frequency/"
edition = "2021"

[dependencies]
codec = { package = "parity-scale-codec", version = "3.0.0" }
jsonrpsee = { version = "0.14.0", features = ["server", "macros"] }

# unfinished
pallet-messages-runtime-api = {default-features = false, path = "../runtime-api" }
common-primitives = {default-features = false, path = "../../../../common/primitives" }
common-helpers = {default-features = false, path = "../../../../common/helpers" }
# Substrate packages
sp-api = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.25" }
sp-blockchain = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.25" }
sp-runtime = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.25" }

[features]
default = ["std"]
std = [
	'codec/std',
	"sp-api/std",
	"sp-runtime/std",
	"pallet-messages-runtime-api/std",
	'common-primitives/std',
]
