[workspace]
members = [
  "node",
  "node/cli",
  "node/service",
  "pallets/*",
  "runtime/*",
  "common/helpers",
]
resolver = "2"

[profile.release]
panic = "unwind"
lto = true
codegen-units = 1
strip = true

# Faster build for bench-dev
[profile.bench-dev]
inherits = "release"
strip = false
codegen-units = 16
lto = false
