[profile.release]
panic = "unwind"

[workspace]
members = [
  "node",
  "node/cli",
  "node/service",
  "pallets/*",
  "runtime/common",
  "runtime/frequency",
  "runtime/frequency-rococo",
  "common/helpers",
]
