[workspace]
members = [
  "node",
  "node/cli",
  "node/service",
  "pallets/*",
  "runtime/*",
  "common/helpers",
]

[profile.release]
panic = "unwind"
lto = true
codegen-units = 1
strip = true

# Faster build for bench-dev
[profile.bench-dev]
inherits = "release"
strip = false
codegen-units = 16
lto = false

# Remove this patch if messages/Cargo.toml::cid dependency is updated to use multihash 0.18.1 or greater
[patch."https://github.com/multiformats/rust-cid"]
multihash = "0.18.1"