[workspace]
members = [
  "node",
  "node/cli",
  "node/service",
  "pallets/*",
  "runtime/*",
  "common/helpers",
]

[profile.release]
panic = "unwind"

[profile.production]
inherits = "release"
lto = true
codegen-units = 1
strip = true

[profile.bench-dev]
inherits = "release"
