coverage:
  precision: 2
  round: down
  range: "60...100"
  status:                        # this controls whether a pull request will be blocked by a decrease in coverage
    # Learn more at https://docs.codecov.com/docs/commit-status
    project:
      default:
        threshold: 5%            # allows coverage to drop by up to the percent noted and still post a success status
        
        # Codecov adds Substrate's weight and benchmarking functions to
        # coverage, which are not testable. The result is a coverage threshold
        # that we cannot meet. Until we find a way arouund that, let's make the
        # coverage report informational only.
        informational: true     # If true is specified the resulting status will pass no matter what the coverage is or what other settings are specified

ignore:
  - "node"  # ignore folders and all its contents
  - "runtime"  # ignore folders and all its contents
