version: '3'
services:
  mrc_alice:
    container_name: mrc-alice
    build:
      context: .
      dockerfile: Dockerfile.devnet
    ports:
      - "30355:30333"
      - "9936:9933"
      - "9946:9944"
    volumes:
      - type: bind
        source: ./res/rococo-local.json
        target: /chainspec.json
        read_only: true
    command: >
      --chain="${RAW_PARACHAIN_CHAIN_SPEC:-./res/genesis/rococo-local-mrc-2000-raw.json}" 
      --alice
      --wasm-execution=compiled
      --execution=wasm
      --rpc-external
      --rpc-cors all
      --ws-external
      --rpc-methods=Unsafe
      --state-cache-size=0
      --log="main,info"
      -- 
      --wasm-execution=compiled 
      --execution=wasm
      --chain=/chainspec.json 
      --bootnodes="/ip4/127.0.0.1/tcp/30333/p2p/12D3KooWDLpRT9KFo6pKdkmdQQt599tmqVYpoeiHemY32Gf4RUpp"
      --bootnodes="/ip4/127.0.0.1/tcp/30344/p2p/12D3KooWKpaJZbNymrZmKG6BNNDC58z8p9YKDXfZtyhEjktgtph4"
