[package]
name = "pallet-schemas-rpc"
version = "0.1.0"
description = "RPC package for schemas"
authors = ["MRC Team"]
license = "Apache-2.0"
publish = false
homepage = "https://unfinishedlabs.io/"
repository = "https://github.com/libertyDSNP/mrc/"
edition = "2021"

[dependencies]
codec = { package = "parity-scale-codec", version = "3.0.0" }
jsonrpc-core = "18.0"
jsonrpc-core-client = "18.0"
jsonrpc-derive = "18.0"

# unfinished
pallet-schemas-runtime-api = { path = "../runtime-api", default-features = false }
common-primitives = { path = '../../../../common/primitives', default-features = false }

# Substrate
sp-api = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.18" }
sp-runtime = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.18" }
sp-blockchain = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.18" }

[features]
default = ["std"]
std = [
	"codec/std",
	"sp-api/std",
	"sp-runtime/std",
	"pallet-schemas-runtime-api/std",
	"common-primitives/std",
]
