[package]
name = "pallet-msa-rpc"
version = '0.1.0'
description = 'A package that adds RPC to Msa pallet'
authors = ['MRC Team']
license = "Apache-2.0"
publish = false
homepage = "https://unfinishedlabs.io/"
repository = "https://github.com/LibertyDSNP/mrc/"
edition = "2021"

[dependencies]
codec = { package = "parity-scale-codec", version = "3.0.0" }
jsonrpc-core = "18.0"
jsonrpc-core-client = "18.0"
jsonrpc-derive = "18.0"
rayon = "1.5"

# unfinished
pallet-msa-runtime-api = {default-features = false, path = "../runtime-api" }
common-primitives = {default-features = false, path = "../../../../common/primitives" }

# Substrate packages
sp-api = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.18" }
sp-std = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.18" }
sp-blockchain = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.18" }
sp-runtime = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.18" }

[features]
default = ["std"]
std = [
	'codec/std',
	"sp-api/std",
	"sp-runtime/std",
	"pallet-msa-runtime-api/std",
	'common-primitives/std',
]
