[package]
name = "pallet-stateful-storage-rpc"
version = "0.0.0"
description = "RPC package for stateful storage"
authors = ["Frequency"]
license = "Apache-2.0"
publish = false
homepage = "https://frequency.xyz"
repository = "https://github.com/libertyDSNP/frequency/"
edition = "2021"

[dependencies]
codec = { package = "parity-scale-codec", version = "3.2.2" }
jsonrpsee = { version = "0.16.2", features = ["client-core", "server", "macros"] }
# Frequency crates
pallet-stateful-storage-runtime-api = { path = "../runtime-api", default-features = false }
common-primitives = { path = '../../../../common/primitives', default-features = false }
common-helpers = { path = '../../../../common/helpers', default-features = false }
# Substrate crates
frame-support = { default-features = false, git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.43" }
sp-core = { default-features = false, git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.43" }
sp-api = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.43" }
sp-rpc = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.43" }
sp-runtime = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.43" }
sp-blockchain = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.43" }
sp-std = { default-features = false, git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.43" }

[dev-dependencies]
tokio = { version = "1.25.0", features = ["macros", "time", "parking_lot"] }
substrate-test-runtime-client = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.43" }
sc-client-api = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.43" }

[features]
default = ["std"]
std = [
	"sp-std/std",
	"codec/std",
	"sp-api/std",
	"sp-core/std",
	"sp-runtime/std",
	"pallet-stateful-storage-runtime-api/std",
	"common-primitives/std",
	"common-helpers/std",
]
