[package]
authors = ["Frequency Team"]
description = "A package that defines common primitives used in runtime and RPCs"
edition = "2021"
homepage = "https://frequency.xyz"
license = "Apache-2.0"
name = 'common-primitives'
publish = false
repository = "https://github.com/LibertyDSNP/frequency/"
version = "0.1.0"

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[dependencies]
codec = {package = "parity-scale-codec", version = "3.1.5", default-features = false, features = ["derive"]}
impl-serde = {version = "0.4.0", default-features = false}
scale-info = {version = "2.1.2", default-features = false, features = ["derive"]}
serde = { version = "1.0.144", default-features = false, features = ["derive"] }

frame-support = {default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.28" }
sp-runtime = {git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.28" }
sp-std = {git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.28" }
smallvec = "1.9.0"
sp-api = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.28" }
sp-core = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.28" }

#ORML
orml-utilities = {git = "https://github.com/open-web3-stack/open-runtime-module-library", default-features = false, branch = "polkadot-v0.9.28"}

[features]
default = ['std']
std = [
  'codec/std',
  'frame-support/std',
  'sp-std/std',
  'sp-runtime/std',
  'sp-api/std',
]
