[package]
authors = ["MRC Team"]
description = "A package that defines common primitives used in runtime and RPCs"
edition = "2021"
homepage = "https://unfinishedlabs.io/"
license = "Apache-2.0"
name = 'common-primitives'
publish = false
repository = "https://github.com/LibertyDSNP/mrc/"
version = "0.1.0"

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[dependencies]
codec = {package = "parity-scale-codec", version = "3.0.0", default-features = false, features = ["derive"]}
frame-support = {default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.18"}
impl-serde = {version = "0.3.1", optional = true}
scale-info = {version = "2.0.1", default-features = false, features = ["derive"]}
serde = {version = "1.0.136", features = ["derive"], optional = true, default-features = false}
sp-runtime = {git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.18"}
sp-std = {git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.18"}

[features]
default = ['std']
std = [
  'codec/std',
  'serde',
  'impl-serde',
  'frame-support/std',
  'sp-std/std',
  'sp-runtime/std',
]
