[package]
authors = ["Frequency"]
description = "A package that defines common primitives used in runtime and RPCs"
edition = "2021"
homepage = "https://frequency.xyz"
license = "Apache-2.0"
name = "common-primitives"
publish = false
repository = "https://github.com/LibertyDSNP/frequency/"
version = "0.0.0"

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[dependencies]
codec = { package = "parity-scale-codec", version = "3.2.2", default-features = false, features = [
  "derive",
] }
frame-support = { default-features = false, git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.43" }
frame-system = { default-features = false, git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.43" }
impl-serde = { version = "0.4.0", default-features = false }
scale-info = { version = "2.5.0", default-features = false, features = [
  "derive",
] }
serde = { version = "1.0.163", default-features = false, features = ["derive"] }
serde_json = { version = "1.0.86", default-features = false, features = [
  "alloc",
] }
enumflags2 = "0.7.7"
smallvec = "1.10.0"
sp-api = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.43" }
sp-core = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.43" }
sp-runtime = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.43" }
sp-std = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.43" }

[features]
default = ['std']
runtime-benchmarks = []
std = [
  'codec/std',
  'frame-support/std',
  'sp-std/std',
  'sp-runtime/std',
  'sp-api/std',
]
