[package]
authors = ["MRC Team"]
description = "A package that defines common primitives used in runtime and RPCs"
edition = "2021"
homepage = "https://unfinishedlabs.io/"
license = "Apache-2.0"
name = 'common-primitives'
publish = false
repository = "https://github.com/LibertyDSNP/mrc/"
version = "0.1.0"

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[dependencies]
codec = {package = "parity-scale-codec", version = "3.0.0", default-features = false, features = ["derive"]}

[features]
default = ['std']
std = [
  'codec/std',
]
