[package]
authors = ["Frequency Team"]
build = "build.rs"
description = "Substrate node for Frequency"
edition = "2021"
homepage = "https://frequency.xyz"
license = "Apache-2.0"
name = "frequency"
repository = "https://github.com/LibertyDSNP/frequency/"
version = "0.1.0"

[[bin]]
name = "frequency"
path = "src/main.rs"

[dependencies]
# Frequency Runtime
frequency-cli = {path = "cli"}
frequency-rococo-runtime = {path = "../runtime/frequency-rococo", optional = true}
frequency-runtime = {path = "../runtime/frequency", optional = true}
frequency-service = {path = "service"}
# Substrate
sc-cli = {git = "https://github.com/paritytech/substrate", features = ["wasmtime"], branch = "polkadot-v0.9.27" }

[build-dependencies]
substrate-build-script-utils = {git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.27" }

[features]
std = []
default = ["std"]
runtime-benchmarks = [
  "frequency-runtime/runtime-benchmarks",
  "frequency-rococo-runtime/runtime-benchmarks",
  "frequency-cli/runtime-benchmarks",
]
frequency = ["frequency-service/frequency", "frequency-cli/frequency"]
frequency-rococo-local = ["frequency-service/frequency-rococo-local", "frequency-cli/frequency-rococo-local"]
frequency-rococo-testnet = ["frequency-service/frequency-rococo-testnet", "frequency-cli/frequency-rococo-testnet"]
all-frequency-features =["frequency-service/all-frequency-features", "frequency-cli/all-frequency-features"]
try-runtime = ["frequency-runtime/try-runtime", "frequency-rococo-runtime/try-runtime"]
