name: Release JS Frequency API Augment Package
on:
  release:
    types: [ released ]
    tags:
      - js-frequency-api-augment-v*
jobs:
  publish-to-npm:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
          registry-url: 'https://registry.npmjs.org'
          cache-dependency-path: js/api-augment/package-lock.json

      - name: Install 💾
        run: npm ci

      - name: Build
        run: npm run build
        working-directory: js/api-augment
        env:
          FULL_SHA: ${{ github.sha }}

      - name: Version ⬆️
        run: npm version --new-version ${{ github.event.release.tag_name }} --no-git-tag-version
        working-directory: js/api-augment/dist

      - name: Publish 🚂
        run: npm publish --tag latest
        working-directory: js/api-augment/dist
        env:
          NODE_AUTH_TOKEN: ${{secrets.NODE_AUTH_TOKEN}}
