name: Reset Self-hosted Runner
description: Shared action that allows to reset a runner to its original state
runs:
  using: "composite"
  steps:
    - name: Remove Cargo Generated Artifacts
      shell: bash
      run: |
        echo "Removing generated cargo artifacts..."
        sudo rm -fr ./target
        sudo rm -rf ./runtime/frequency/target
    - name: Remove NPM node Modules
      shell: bash
      run: |
        find . -name 'node_modules' -type d -prune -exec rm -rf '{}' +
    - name: Prune docker Resources
      shell: bash
      run: |
        if [ "$(which docker)" ] && [ "$(docker --version)" ]; then
          echo "Docker is found. Cleaning..."
          docker system prune -a --volumes
          docker image prune -a -f --filter "until=720h"
          echo "Finished cleaning docker resources."
        else
          echo "Docker's not found. Exiting..."
          exit 0
        fi
