[package]
authors = ["Frequency"]
description = "Substrate cli for frequency node"
edition = "2021"
homepage = "https://unfinishedlabs.io/"
license = "Apache-2.0"
name = "frequency-cli"
repository = "https://github.com/LibertyDSNP/frequency/"
version = "0.0.0"

[dependencies]
clap = { version = "4.0.17", features = ["derive"] }
codec = { package = "parity-scale-codec", version = "3.1.5" }
derive_more = "0.99.17"
hex-literal = "0.3.4"
log = "0.4.17"
serde_json = "1.0.86"
serde = { version = "1.0.145", features = ["derive"] }
# Frequency Runtime
common-primitives = { default-features = false, path = "../../common/primitives" }
frequency-service = { package = "frequency-service", path = "../service", default-features = false, optional = true }
# Substrate
frame-benchmarking-cli = { git = "https://github.com/paritytech/substrate", optional = true, branch = "polkadot-v0.9.33" }
sc-cli = { git = "https://github.com/paritytech/substrate", features = [
  "wasmtime"
], optional = true, branch = "polkadot-v0.9.33" }
sc-service = { git = "https://github.com/paritytech/substrate", features = [
  "wasmtime"
], optional = true, branch = "polkadot-v0.9.33" }
sc-sysinfo = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.33" }
sc-telemetry = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.33" }
sc-tracing = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.33" }
sp-api = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.33" }
sp-core = { git = "https://github.com/paritytech/substrate", optional = true, branch = "polkadot-v0.9.33" }
sp-runtime = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.33" }
try-runtime-cli = { git = "https://github.com/paritytech/substrate", optional = true, branch = "polkadot-v0.9.33" }
# Polkadot
polkadot-cli = { git = "https://github.com/paritytech/polkadot", branch = "release-v0.9.33" }
polkadot-parachain = { git = "https://github.com/paritytech/polkadot", branch = "release-v0.9.33" }
polkadot-primitives = { git = "https://github.com/paritytech/polkadot", branch = "release-v0.9.33" }
polkadot-service = { git = "https://github.com/paritytech/polkadot", branch = "release-v0.9.33" }
# Cumulus
cumulus-client-cli = { git = "https://github.com/paritytech/cumulus", branch = "polkadot-v0.9.33" }
cumulus-client-service = { git = "https://github.com/paritytech/cumulus", branch = "polkadot-v0.9.33" }
cumulus-primitives-core = { git = "https://github.com/paritytech/cumulus", branch = "polkadot-v0.9.33" }

[build-dependencies]
substrate-build-script-utils = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.33" }

[features]
std = ["sp-api/std"]
cli = [
  "frequency-service",
  "sp-core",
  "sc-cli",
  "sc-service",
  "frame-benchmarking-cli",
  "try-runtime-cli",
]
default = ["std", "wasmtime", "cli"]
runtime-benchmarks = ["polkadot-cli/runtime-benchmarks"]
try-runtime = ["frequency-service/try-runtime", "try-runtime-cli",  "try-runtime-cli/try-runtime"]
wasmtime = ["sc-cli/wasmtime"]
on-chain-release-build = ["sp-api/disable-logging"]
frequency = ["frequency-service/frequency"]
frequency-rococo-local = ["frequency-service/frequency-rococo-local"]
frequency-rococo-testnet = ["frequency-service/frequency-rococo-testnet"]
all-frequency-features = [
  "frequency",
  "frequency-rococo-local",
  "frequency-rococo-testnet",
  "frequency-service/all-frequency-features"
]

