[package]
authors = ["Frequency Team"]
description = "Substrate cli for frequency node"
edition = "2021"
homepage = "https://unfinishedlabs.io/"
license = "Apache-2.0"
name = "frequency-cli"
repository = "https://github.com/LibertyDSNP/frequency/"
version = "0.1.0"

[dependencies]
clap = {version = "3.2.20", features = ["derive"]}
codec = {package = "parity-scale-codec", version = "3.1.5"}
derive_more = "0.99.17"
hex-literal = "0.3.4"
log = "0.4.17"
serde = {version = "1.0.144", features = ["derive"]}

# Frequency Runtime
common-primitives = {default-features = false, path = "../../common/primitives"}
frequency-service = {package = "frequency-service", path = "../service", default-features = false, optional = true}

# Substrate
frame-benchmarking-cli = {git = "https://github.com/paritytech/substrate", optional = true, branch = "polkadot-v0.9.28" }
sc-cli = {git = "https://github.com/paritytech/substrate", features = ["wasmtime"], optional = true, branch = "polkadot-v0.9.28" }
sc-service = {git = "https://github.com/paritytech/substrate", features = ["wasmtime"], optional = true, branch = "polkadot-v0.9.28" }
sc-sysinfo = {git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.28" }
sc-telemetry = {git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.28" }
sc-tracing = {git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.28" }
sp-core = {git = "https://github.com/paritytech/substrate", optional = true, branch = "polkadot-v0.9.28" }
sp-runtime = {git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.28" }
try-runtime-cli = {git = "https://github.com/paritytech/substrate", optional = true, branch = "polkadot-v0.9.28" }

# Polkadot
polkadot-cli = {git = "https://github.com/paritytech/polkadot", branch = "release-v0.9.28"}
polkadot-parachain = {git = "https://github.com/paritytech/polkadot", branch = "release-v0.9.28"}
polkadot-primitives = {git = "https://github.com/paritytech/polkadot", branch = "release-v0.9.28"}
polkadot-service = {git = "https://github.com/paritytech/polkadot", branch = "release-v0.9.28"}

# Cumulus
cumulus-client-cli = {git = "https://github.com/paritytech/cumulus", branch = "polkadot-v0.9.28" }
cumulus-client-service = {git = "https://github.com/paritytech/cumulus", branch = "polkadot-v0.9.28" }
cumulus-primitives-core = {git = "https://github.com/paritytech/cumulus", branch = "polkadot-v0.9.28" }

[build-dependencies]
substrate-build-script-utils = {git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.28" }

[features]
std = []
cli = [
  "frequency-service",
  "sp-core",
  "sc-cli",
  "sc-service",
  "frame-benchmarking-cli",
  "try-runtime-cli",
]
default = ["std", "wasmtime", "cli"]
runtime-benchmarks = [
  "polkadot-cli/runtime-benchmarks",
]
try-runtime = []
wasmtime = ["sc-cli/wasmtime"]
frequency = ["frequency-service/frequency"]
frequency-rococo-local = ["frequency-service/frequency-rococo-local"]
frequency-rococo-testnet = ["frequency-service/frequency-rococo-testnet"]
all-frequency-features = ["frequency", "frequency-rococo-local", "frequency-rococo-testnet", "frequency-service/all-frequency-features"]
