[package]
authors = ["MRC Team"]
description = "A package that defines common helper modules used in MRC"
edition = "2021"
homepage = "https://unfinishedlabs.io/"
license = "Apache-2.0"
name = 'common-helpers'
publish = false
repository = "https://github.com/LibertyDSNP/mrc/"
version = "0.1.0"

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[dependencies]
apache-avro = { git = "https://github.com/apache/avro", features = ["snappy"] }
thiserror = "1"
sha2 = "0.10.2"
rayon = "1.5"
jsonrpsee = { version = "0.14.0", features = ["server", "macros"] }
sp-runtime = {git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.25"}
sp-api = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.25" }

[dev-dependencies]
proptest = "1.0"

[features]
default = ['std']
std = [
  'sp-runtime/std',
  'sp-api/std',
]
