[package]
authors = ["Frequency Team"]
description = "Pallet for creating MSA"
edition = "2021"
homepage = "https://frequency.xyz"
license = "Apache-2.0"
name = "pallet-msa"
publish = false
repository = "https://github.com/libertyDSNP/frequency/"
version = "0.1.0"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = {package = "parity-scale-codec", version = "3.1.5", default-features = false, features = [
  "derive",
]}
frame-benchmarking = {default-features = false, git = "https://github.com/paritytech/substrate.git", optional = true, branch = "polkadot-v0.9.29"}
frame-support = {default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.29"}
frame-system = {default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.29"}
scale-info = {version = "2.1.2", default-features = false, features = [
  "derive",
]}
sp-core = {default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.29"}
sp-io = { default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.29" }
sp-runtime = {default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.29"}
sp-std = {default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.29"}
# Frequency related dependencies
common-primitives = {default-features = false, path = "../../common/primitives"}
#ORML
orml-utilities = {git = "https://github.com/open-web3-stack/open-runtime-module-library", default-features = false, branch = "polkadot-v0.9.29"}

[dev-dependencies]
common-runtime = {path = '../../runtime/common', default-features = false}
pallet-schemas = {path = "../schemas", default-features = false}

sp-keystore = {default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.29"}

[features]
default = ["std"]
runtime-benchmarks = ["frame-benchmarking/runtime-benchmarks", "pallet-schemas/runtime-benchmarks", "common-primitives/runtime-benchmarks"]
std = [
  "codec/std",
  "scale-info/std",
  "frame-support/std",
  "frame-system/std",
  "frame-benchmarking/std",
  "orml-utilities/std",
  "sp-runtime/std",
  "sp-std/std",
  "sp-core/std",
]
try-runtime = ["frame-support/try-runtime"]
