on:
  push:
    branches:
      - main

name: Build Main
jobs:
  build_prep:
    name: build-prep
    runs-on: "ubuntu-latest"
    outputs:
      matrix: ${{ steps.set-build-param.outputs.matrix }}
    steps:
      # Required as the JSON input file needs to be read
      - uses: actions/checkout@v3
      - id: set-build-param
        uses: JoshuaTheMiller/conditional-build-matrix@b9af2b1b137d7bd7818c1233ef830b326809a7cc
        with:
          inputFile: ".github/workflows/build-params.json"
          # we run build-node on every workflow but build-runtime only on pushes to branches
          filter: "[?run_on_event==`any` || run_on_event==`${{ github.event_name }}`]"
  build:
    needs: build_prep
    strategy:
      matrix: ${{fromJson(needs.build_prep.outputs.matrix)}}
    name: ${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    env:
      RUST_TOOLCHAIN: ${{ matrix.rust_toolchain }}
      DOCKER_HUB_PROFILE: frequencychain
    steps:
      - name: Free space on Ubuntu
        if: ${{ matrix.os }} == 'ubuntu-latest'
        run: |
          echo "Pre cleanup"
          df -h
          sudo rm -rf "/usr/local/share/boost"
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"
          echo "Post cleanup"
          df -h
      - name: Check out code
        uses: actions/checkout@v3
      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ env.RUST_TOOLCHAIN }}
          default: true
      - if: matrix.target == 'build-runtime' || matrix.target == 'build-runtime-rococo'
        uses: Swatinem/rust-cache@v1
        with: # cache the runtime target instead of root target for build-runtime
          working-directory: "./runtime"
          target-dir: "./target/frequency"
      - if: matrix.target == 'build-node'
        uses: Swatinem/rust-cache@v1
      - name: ${{ matrix.target }}
        run: ./ci/build.sh
        env:
          TARGET: ${{ matrix.target }}
          RUST_TOOLCHAIN: ${{ matrix.rust_toolchain }}
          PACKAGE: ${{matrix.package}}
          RUNTIME_DIR: ${{ matrix.dir }}
      - name: Set up QEMU
        if: matrix.target == 'build-node'
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        if: matrix.target == 'build-node'
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        if: matrix.target == 'build-node'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME_FC }}
          password: ${{ secrets.DOCKERHUB_TOKEN_FC }}
      - name: Get the tag name
        if: matrix.target == 'build-node'
        run: |
          date_tag=$(date +'%Y%m%d-%H%M')
          echo ${date_tag}
          echo "TAG=${date_tag}" >> $GITHUB_ENV
      - name: Generate Frequency local chain spec
        if: matrix.target == 'build-node'
        run: ./scripts/generate_specs.sh 2000 rococo-2000
      - name: Build and push collator image for local relay chain
        if: matrix.target == 'build-node'
        env:
          IMAGE_NAME: collator-node-local
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          file: docker/${{env.IMAGE_NAME}}.dockerfile
          tags: |
            ${{env.DOCKER_HUB_PROFILE}}/${{env.IMAGE_NAME}}:${{ env.TAG }}
            ${{env.DOCKER_HUB_PROFILE}}/${{env.IMAGE_NAME}}:latest
      - name: Update DockerHub description for collator image for local relay chain
        if: matrix.target == 'build-node'
        uses: peter-evans/dockerhub-description@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME_FC }}
          password: ${{ secrets.DOCKERHUB_TOKEN_FC }}
          repository: ${{env.DOCKER_HUB_PROFILE}}/collator-node-local
          readme-filepath: docker/collator-node-local.overview.md
      - name: Build and push collator image in instant seal mode
        if: matrix.target == 'build-node'
        env:
          IMAGE_NAME: instant-seal-node
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          file: ./docker/${{env.IMAGE_NAME}}.dockerfile
          tags: |
            ${{env.DOCKER_HUB_PROFILE}}/${{env.IMAGE_NAME}}:${{env.TAG}}
            ${{env.DOCKER_HUB_PROFILE}}/${{env.IMAGE_NAME}}:latest
      - name: Update DockerHub description for collator image in instant seal mode
        if: matrix.target == 'build-node'
        uses: peter-evans/dockerhub-description@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME_FC }}
          password: ${{ secrets.DOCKERHUB_TOKEN_FC }}
          repository: ${{env.DOCKER_HUB_PROFILE}}/instant-seal-node
          readme-filepath: docker/instant-seal-node.overview.md
      - name: Build and push parachain image
        if: matrix.target == 'build-node'
        env:
          IMAGE_NAME: parachain-node
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          file: ./docker/${{env.IMAGE_NAME}}.dockerfile
          tags: |
            ${{env.DOCKER_HUB_PROFILE}}/${{env.IMAGE_NAME}}:${{ env.TAG }}
            ${{env.DOCKER_HUB_PROFILE}}/${{env.IMAGE_NAME}}:latest
      - name: Update DockerHub description for parachain image
        if: matrix.target == 'build-node'
        uses: peter-evans/dockerhub-description@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME_FC }}
          password: ${{ secrets.DOCKERHUB_TOKEN_FC }}
          repository: ${{env.DOCKER_HUB_PROFILE}}/parachain-node
          readme-filepath: docker/parachain-node.overview.md
