name: Run Post PR Merge Actions
concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: true
on:
  push:
    branches:
      - main
    paths:
      - "js/api-augment/**"
      - "**/*.rs"
      - "**/Cargo.toml"
      - "**/Cargo.lock"
env:
  BUILD_PROFILE: release
  RUST_TOOLCHAIN: nightly-2022-09-22

jobs:
  publish-js-api-augment-rc:
    name: Merge - Publish JS API Augment Release Candidate
    runs-on: [self-hosted, Linux, X64]
    steps:
      - name: Set Env Vars
        run: |
          echo "HOME=/root" >> $GITHUB_ENV
      - name: Check Out Repo
        uses: actions/checkout@v3
      - name: Install Rust Toolchain
        uses: actions-rs/toolchain@16499b5e05bf2e26879000db0c1d13f7e13fa3af
        with:
          toolchain: ${{env.RUST_TOOLCHAIN}}
          default: true
          profile: minimal
          target: wasm32-unknown-unknown
      - name: Check Out Repo
        uses: actions/checkout@v3
      # - name: Save/Restore Dependencies from Cache
      #   uses: Swatinem/rust-cache@359a70e43a0bb8a13953b04a90f76428b4959bb6
      #   with:
      #     shared-key: ${{env.RUST_TOOLCHAIN}}
      - name: Output Metadata
        # Run the cargo command and ignore any extra lines outside of the json result
        run: CARGO_INCREMENTAL=0 RUSTFLAGS="-D warnings" cargo run --features frequency export-metadata ./js/api-augment/metadata.json
      - name: Set up NodeJs
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "npm"
          registry-url: "https://registry.npmjs.org"
          cache-dependency-path: js/api-augment/package-lock.json
      - name: Install
        run: npm ci
        working-directory: js/api-augment
      - name: Build
        run: npm run build
        working-directory: js/api-augment
        env:
          FULL_SHA: ${{github.sha}}
      - name: Version Package
        run: npm version --new-version "v0.0.0-${FULL_SHA:0:6}" --no-git-tag-version
        working-directory: js/api-augment/dist
        env:
          FULL_SHA: ${{github.sha}}
      # - name: Publish on NPM @next
      #   run: npm publish --tag next --access public
      #   working-directory: js/api-augment/dist
      #   env:
      #     NODE_AUTH_TOKEN: ${{secrets.NODE_AUTH_TOKEN}}

  calc-code-coverage-main:
    name: Merge - Calculate Code Coverage
    runs-on: ubuntu-20.04
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v3
      - name: Install Required Packages
        run: |
          sudo apt-get update
          sudo apt install -y protobuf-compiler
      - name: Install Rust Toolchain
        uses: actions-rs/toolchain@16499b5e05bf2e26879000db0c1d13f7e13fa3af
        with:
          default: true
          profile: minimal
          target: wasm32-unknown-unknown
          toolchain: stable
      - name: Run cargo-tarpaulin
        uses: actions-rs/tarpaulin@044a1e5bdace8dd2f727b1af63c1d9a1d3572068
        with:
          version: "0.22.0"
          # Tarpaulin Docs https://github.com/xd009642/tarpaulin
          # -e for exclude
          args: |
            -v --no-fail-fast --workspace
            -e frequency frequency-cli frequency-runtime frequency-service
            --exclude-files **/mock.rs **/weights.rs **/weights/* **/benchmarking.rs
      # - name: Upload to codecov.io
      #   uses: codecov/codecov-action@v3
      #   with:
      #     fail_ci_if_error: false # optional (default = false)
      #     verbose: true # optional (default = false)
