name: Merge PR
concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: true
on:
  push:
    branches:
      - main
    paths:
      - "js/api-augment/**"
      - "**/*.rs"
      - "**/Cargo.toml"
      - "**/Cargo.lock"
env:
  BUILD_PROFILE: release

jobs:
  publish-js-api-augment-rc:
    name: Merge - Publish JS API Augment Release Candidate
    env:
      HOME: /root
    runs-on: [self-hosted, Linux, X64, build]
    container: ubuntu:20.04
    steps:
      - name: Install Required Packages
        run: |
          apt-get update
          apt-get install -y curl protobuf-compiler build-essential libclang-dev
      - name: Check Out Repo
        uses: actions/checkout@v3
      - name: Install Rust Toolchain
        uses: dtolnay/rust-toolchain@e12eda571dc9a5ee5d58eecf4738ec291c66f295
        with:
          targets: wasm32-unknown-unknown
          toolchain: stable
      - name: Output Metadata
        # Run the cargo command and ignore any extra lines outside of the json result
        run: CARGO_INCREMENTAL=0 RUSTFLAGS="-D warnings" cargo run --features frequency-rococo-local -- export-metadata  --chain=frequency-local --tmp ./js/api-augment/metadata.json
      - name: Set up NodeJs
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "npm"
          registry-url: "https://registry.npmjs.org"
          cache-dependency-path: js/api-augment/package-lock.json
      - name: Install
        run: npm ci
        working-directory: js/api-augment
      - name: Build
        run: npm run build
        working-directory: js/api-augment
        env:
          FULL_SHA: ${{github.sha}}
      - name: Version Package
        env:
          FULL_SHA: ${{github.sha}}
        working-directory: js/api-augment/dist
        shell: bash
        run: npm version --new-version "v0.0.0-${FULL_SHA:0:6}" --no-git-tag-version
      - name: Publish on NPM @next
        run: npm publish --tag next --access public
        working-directory: js/api-augment/dist
        env:
          NODE_AUTH_TOKEN: ${{secrets.NODE_AUTH_TOKEN}}

  calc-code-coverage:
    name: Merge - Calculate Code Coverage
    runs-on: [self-hosted, Linux, X64, build]
    container: ubuntu:20.04
    steps:
      - name: Install Required Packages
        run: |
          apt-get update
          apt-get install -y curl protobuf-compiler build-essential libclang-dev git
          git --version
      - name: Check Out Repo
        uses: actions/checkout@v3
      - name: Install Rust Toolchain
        uses: dtolnay/rust-toolchain@e12eda571dc9a5ee5d58eecf4738ec291c66f295
        with:
          targets: wasm32-unknown-unknown
          toolchain: stable
      - name: Generate and Upload Code Coverage
        id: codecov
        uses: ./.github/workflows/common/codecov
