# This workflow is used only when a development version of CI base image needs to be built.
name: Publish Dev CI Base Image
concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: true
on:
  push:
    branches:
      - disabled-as-this-branch-does-not-exist
      # - 1482-add-rust-toolchain-install-to-ci-base-image
env:
  BIN_DIR: target/release

jobs:
  publish-ci-base-image:
    name: Publish CI Base Image
    env:
      # IMAGE_NAME: ci-base-image-dind
      IMAGE_NAME: ci-base-image
      BRANCH_NAME: ${{github.ref_name}}
    runs-on: ubuntu-20.04
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: "amd64"
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
      - name: Sanitize repo owner slug
        uses: actions/github-script@v6
        id: repo_slug
        with:
          result-encoding: string
          script: return `ghcr.io/${context.repo.owner.toLowerCase()}/${context.repo.repo.toLowerCase()}`
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: tools/ci/docker
          push: true
          file: tools/ci/docker/ci-base-image.dockerfile
          tags: |
            ${{steps.repo_slug.outputs.result}}/${{env.IMAGE_NAME}}:${{env.BRANCH_NAME}}
