name: Publish JS Frequency RPC Package @next
defaults:
  run:
    working-directory: js/rpc
on:
  push:
    branches: [ main ]
    paths:
      - 'js/rpc'
jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'

      - name: Install 💾
        run: npm ci

      - name: Version ⬆️
        run: npm version --new-version "v0.0.0-${FULL_SHA:0:6}" --no-git-tag-version
        env:
          FULL_SHA: ${{ github.sha }}

      - name: Publish @next 🚂
        run: npm publish --tag next --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NODE_AUTH_TOKEN}}
