# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Rococo E2E Tests
run-name: Rococo E2E Testing ${{github.event.inputs.release-version || github.ref_name}}
concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: true
on:
  workflow_dispatch:
    inputs:
      release-version:
        description: "Test Release version (v#.#.#[-rc#])"
        required: true

env:
  TAG_FROM_UI: ${{github.event.inputs.release-version}}

jobs:
  run-e2e:
    name: Run E2E Tests
    runs-on: ubuntu-22.04
    container: ghcr.io/frequency-chain/frequency/ci-base-image:1.3.1
    steps:
      - name: Validate
        shell: bash
        run: |
          version=${{env.TAG_FROM_UI}}
          echo "Release version entered in UI: $version"
          regex='^v([0-9]+)\.(0|([1-9][0-9]*))\.(0|([1-9][0-9]*))(-rc[1-9][0-9]*)?$'
          if [[ ! $version =~ $regex ]]; then
            echo "ERROR: Entered version $version is not valid."
            echo "Please use v#.#.#[-rc#] format."
            exit 1
          fi
      - name: Check Out Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{env.TAG_FROM_UI}}
      - name: Set Env Vars
        run: |
          echo "API_AUGMENT_VERSION=$(echo ${{ env.TAG_FROM_UI }} | sed 's/^v//')" >> $GITHUB_ENV
      - name: Set up NodeJs
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
          cache-dependency-path: e2e/package-lock.json
      - name: Install Built api-augment
        run: npm install @frequency-chain/api-augment@${{ env.API_AUGMENT_VERSION }}
        working-directory: e2e
      - name: Run e2e Tests
        working-directory: e2e
        env:
          CHAIN_ENVIRONMENT: rococo-testnet
          WS_PROVIDER_URL: wss://rpc.rococo.frequency.xyz
          FUNDING_ACCOUNT_SEED_PHRASE: ${{ secrets.ROCOCO_E2E_TEST_SEED_PHRASE }}
        run: npm run test:relay
