name: Verify PR Commit
concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: true
on:
  pull_request:
    branches: [main]
env:
  RUST_TOOLCHAIN: nightly-2022-07-23

jobs:
  changes:
    name: Determine Changed Files
    runs-on: ubuntu-latest
    outputs:
      rust: ${{steps.filter.outputs.rust}}
      js: ${{steps.filter.outputs.rust}}
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v3
      - name: Check for Changed Files
        uses: dorny/paths-filter@v2.10.2
        id: filter
        with:
          filters: |
            rust:
              - '**/*.rs'
              - '**/*.hbs'
              - '.rustfmt.toml'
              - '**/Cargo.toml'
              - '**/Cargo.lock'
            js:
              - "js/**"

  compile-project:
    needs: changes
    if: ${{needs.changes.outputs.rust == 'true'}}
    name: Compile Frequency Project
    runs-on: ubuntu-latest
    steps:
      - name: Install Rust Toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{env.RUST_TOOLCHAIN}}
          default: true
          profile: minimal
          target: wasm32-unknown-unknown
      - name: Check Out Repo
        uses: actions/checkout@v3
      - name: Save/Restore Dependencies from Cache
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: ${{env.RUST_TOOLCHAIN}}
      - name: Cache Frequency Binary
        uses: actions/cache@v3
        with:
          path: |
            target/release/frequency
          key: ${{runner.os}}-${{env.RUST_TOOLCHAIN}}-${{github.sha}}
      - name: Compile
        run: |
          CARGO_INCREMENTAL=0 RUSTFLAGS="-D warnings" cargo build --locked --release --features  frequency

  check-rust-code-format:
    needs: changes
    if: ${{needs.changes.outputs.rust == 'true'}}
    name: Check Rust Code Format
    runs-on: ubuntu-latest
    steps:
      - name: Install Rust Toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{env.RUST_TOOLCHAIN}}
          default: true
          profile: minimal
          components: rustfmt
      - name: Check Out Repo
        uses: actions/checkout@v3
      - name: Check
        run: cargo fmt --check

  lint-rust-code:
    needs: changes
    if: ${{needs.changes.outputs.rust == 'true'}}
    name: Lint Rust Code
    runs-on: ubuntu-latest
    steps:
      - name: Install Rust Toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{env.RUST_TOOLCHAIN}}
          default: true
          profile: minimal
          components: clippy
      - name: Check Out Repo
        uses: actions/checkout@v3
      - name: Lint
        run: |
          SKIP_WASM_BUILD=1 env -u RUSTFLAGS cargo clippy --features all-frequency-features -- -D warnings

  check-rust-docs:
    needs: changes
    if: ${{needs.changes.outputs.rust == 'true'}}
    name: Check Rust Docs
    runs-on: ubuntu-latest
    steps:
      - name: Install Rust Toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{env.RUST_TOOLCHAIN}}
          default: true
          profile: minimal
          target: wasm32-unknown-unknown
          components: rust-docs
      - name: Check Out Repo
        uses: actions/checkout@v3
      - name: Build Rust Docs
        run: RUSTDOCFLAGS="--enable-index-page --check -Zunstable-options" cargo doc --no-deps

  check-rust-packages-and-deps:
    needs: changes
    if: ${{needs.changes.outputs.rust == 'true'}}
    name: Check Rust Packages and Dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Install Rust Toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{env.RUST_TOOLCHAIN}}
          default: true
          profile: minimal
          components: rust-docs
      - name: Check Out Repo
        uses: actions/checkout@v3
      - name: Check
        run: SKIP_WASM_BUILD= cargo check --features  frequency

  run-rust-tests:
    needs: changes
    if: ${{needs.changes.outputs.rust == 'true'}}
    name: Run Rust Tests
    runs-on: ubuntu-latest
    steps:
      - name: Install Rust Toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{env.RUST_TOOLCHAIN}}
          default: true
          profile: minimal
          target: wasm32-unknown-unknown
      - name: Check Out Repo
        uses: actions/checkout@v3
      - name: Restore Dependencies from Cache
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: ${{env.RUST_TOOLCHAIN}}
      - name: Run Tests
        run: cargo test --all-features --workspace --release

  calc-code-coverage:
    needs: changes
    if: ${{needs.changes.outputs.rust == 'true'}}
    name: Calculate Code Coverage
    runs-on: ubuntu-latest
    steps:
      - name: Install Rust Toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{env.RUST_TOOLCHAIN}}
          default: true
          profile: minimal
          target: wasm32-unknown-unknown
      - name: Check Out Repo
        uses: actions/checkout@v3
      - name: Run cargo-tarpaulin
        uses: actions-rs/tarpaulin@v0.1
        with:
          version: "0.20.1"
          # Tarpaulin Docs https://github.com/xd009642/tarpaulin
          # -e for exclude
          args: |
            -v --no-fail-fast --workspace
            -e frequency frequency-cli frequency-runtime frequency-rococo-runtime frequency-service
            --exclude-files **/mock.rs **/weights.rs **/weights/*
      - name: Upload to codecov.io
        uses: codecov/codecov-action@v3
        with:
          fail_ci_if_error: false # optional (default = false)
          verbose: true # optional (default = false)

  verify-js-api-augment:
    needs: changes
    if: ${{needs.changes.outputs.js == 'true'}}
    name: Verify JS API Augment
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v3
      - name: Set up NodeJs
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "npm"
          cache-dependency-path: js/api-augment/package-lock.json
      - name: Install
        run: npm ci
        working-directory: js/api-augment
      - name: Lint
        run: npm run lint
        working-directory: js/api-augment
      - name: Test
        run: npm test
        working-directory: js/api-augment
      - name: Build
        run: npm run build
        working-directory: js/api-augment
      - name: Build & Publish Dry Run
        run: npm publish --dry-run
        working-directory: js/api-augment/dist

  verify-docker-images:
    needs: compile-project
    name: Verify Docker Images
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v3
      - name: Install Rust Toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{env.RUST_TOOLCHAIN}}
          default: true
          profile: minimal
          # target: wasm32-unknown-unknown
      - name: Restore Dependencies from Cache
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: ${{env.RUST_TOOLCHAIN}}
      - name: Restore Frequency Binary from Cache
        uses: actions/cache@v3
        with:
          path: |
            target/release/frequency
          key: ${{runner.os}}-${{env.RUST_TOOLCHAIN}}-${{github.sha}}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build collator image in instant seal mode
        env:
          IMAGE_NAME: instant-seal-node
        uses: docker/build-push-action@v3
        with:
          context: .
          push: false
          file: ./docker/${{env.IMAGE_NAME}}.dockerfile
      - name: Build collator image for local relay chain
        env:
          IMAGE_NAME: collator-node-local
        uses: docker/build-push-action@v3
        with:
          context: .
          push: false
          file: docker/${{env.IMAGE_NAME}}.dockerfile

  execute-runtime-checks:
    needs: compile-project
    name: Execute Runtime Checks
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v3
      - name: Install Rust Toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{env.RUST_TOOLCHAIN}}
          default: true
          profile: minimal
          # target: wasm32-unknown-unknown
      - name: Restore Dependencies from Cache
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: ${{env.RUST_TOOLCHAIN}}
      - name: Restore Frequency Binary from Cache
        uses: actions/cache@v3
        with:
          path: |
            target/release/frequency
          key: ${{runner.os}}-${{env.RUST_TOOLCHAIN}}-${{github.sha}}
      - name: Check Binary Version
        run: |
          file ./target/release/frequency && ./target/release/frequency --version
